**workflow**
+ credit card data
+ data pre-processing
+ data analysis
+ train test split
+ logistic regression model
+ evaluation

importing the dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [5]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [6]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
188256,127893.0,-8.852104,-11.509369,0.449332,2.068166,5.423514,-4.506990,-3.722182,-0.343961,-1.255238,...,-1.390078,1.059268,5.788621,1.226642,1.186211,0.584517,1.783203,-0.400900,37.5,0.0
188257,127894.0,1.609287,-0.581437,0.008484,1.655629,-1.162795,-0.938786,-0.287847,-0.124818,0.855258,...,0.373621,0.902301,0.129504,0.858324,-0.281039,-0.628079,0.032977,0.003303,150.0,0.0
188258,127894.0,2.097886,-0.685229,-1.281921,-0.318993,-0.235987,-0.167462,-0.382762,-0.114099,-0.412410,...,-0.136930,0.381340,0.056371,0.740105,0.272978,-0.107836,0.016936,-0.057214,11.5,0.0
188259,127894.0,1.851731,-0.368532,0.157316,1.422273,-0.917616,-0.315417,-0.696940,0.053708,1.206733,...,0.073982,0.288365,0.247731,-0.001908,-0.361825,-0.760861,0.069835,-0.013513,45.0,0.0
188260,127894.0,1.759307,-0.459599,-0.379355,1.665059,-0.555768,-0.275380,-0.174480,0.001335,1.259834,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188261 entries, 0 to 188260
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    188261 non-null  float64
 1   V1      188261 non-null  float64
 2   V2      188261 non-null  float64
 3   V3      188261 non-null  float64
 4   V4      188261 non-null  float64
 5   V5      188261 non-null  float64
 6   V6      188261 non-null  float64
 7   V7      188261 non-null  float64
 8   V8      188261 non-null  float64
 9   V9      188261 non-null  float64
 10  V10     188261 non-null  float64
 11  V11     188261 non-null  float64
 12  V12     188261 non-null  float64
 13  V13     188260 non-null  float64
 14  V14     188260 non-null  float64
 15  V15     188260 non-null  float64
 16  V16     188260 non-null  float64
 17  V17     188260 non-null  float64
 18  V18     188260 non-null  float64
 19  V19     188260 non-null  float64
 20  V20     188260 non-null  float64
 21  V21     188260 non-null  float64
 22  V22     188260 non-null  float64
 23  V23     188260 non-null  float64
 24  V24     188260 non-null  float64
 25  V25     188260 non-null  float64
 26  V26     188260 non-null  float64
 27  V27     188260 non-null  float64
 28  V28     188260 non-null  float64
 29  Amount  188260 non-null  float64
 30  Class   188260 non-null  float64
dtypes: float64(31)
memory usage: 44.5 MB

In [8]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    187892
1.0       368
Name: count, dtype: int64

this dataset is highly imbalanced

0 --> normal transaction

1 --> fraudulent transaction

In [10]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
print(legit.shape)
print(fraud.shape)

(187892, 31)
(368, 31)

In [12]:
# statistical measures of the data
legit.Amount.describe()

count    187892.000000
mean         88.949661
std         247.532742
min           0.000000
25%           5.960000
50%          22.750000
75%          79.000000
max       19656.530000
Name: Amount, dtype: float64

In [13]:
fraud.Amount.describe()

count     368.000000
mean      115.659891
std       248.444604
min         0.000000
25%         1.000000
50%        11.395000
75%       104.007500
max      2125.870000
Name: Amount, dtype: float64

In [14]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,66928.356710,-0.115473,0.005839,0.398688,0.079599,-0.127383,0.05489,-0.048754,0.021358,0.018046,...,0.023277,-0.020226,-0.06081,-0.018125,0.006229,0.072192,0.008418,0.001399,0.002064,88.949661
1.0,58116.711957,-5.926741,4.330987,-7.884388,4.836685,-4.286202,-1.42407,-6.893932,0.739547,-2.838131,...,0.404833,0.790022,-0.02306,-0.043940,-0.071941,0.080214,0.040915,0.177371,0.050569,115.659891

under-sampling

build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

number of fraudulent transactions --> 492

In [16]:
legit_sample = legit.sample(n=492)

concatenating two dataframes

In [17]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [18]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
163637,116108.0,1.904875,-0.039293,-1.861770,0.590780,0.141073,-1.397079,0.346124,-0.370206,0.624711,...,0.234132,0.673027,-0.087906,-0.160303,0.209953,-0.101097,-0.014327,-0.017435,79.80,0.0
111899,72420.0,1.464097,-0.417452,0.184517,-0.893352,-0.579609,-0.458066,-0.508178,-0.179101,-0.825080,...,-0.147869,-0.509332,-0.000225,-0.575871,0.388285,-0.423453,0.013825,0.015681,14.39,0.0
173145,121366.0,2.293280,-0.705780,-1.718465,-1.180551,0.164643,-0.159485,-0.416908,-0.181577,-0.343069,...,-0.143973,-0.396187,0.191255,-0.383015,-0.019366,-0.368746,-0.030408,-0.062015,7.95,0.0
123688,77024.0,0.584567,-1.233131,1.400068,1.754818,-1.247584,1.550662,-0.951445,0.604287,1.534106,...,0.120765,0.307101,-0.313366,-0.259121,0.393065,-0.214801,0.073843,0.060423,237.89,0.0
164510,116772.0,-0.369700,0.764911,0.079105,1.237013,1.391318,-0.237741,0.772740,-0.061672,-0.411669,...,0.201544,0.732222,-0.150214,0.545925,-0.091192,-0.391430,0.228385,0.237752,36.12,0.0

In [19]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
178208,123525.0,-5.904921,4.439911,-8.631802,7.788684,-4.989580,-1.200144,-7.674060,4.125761,-5.315778,...,1.775030,1.266441,-0.199410,0.014960,-0.000019,0.544210,-1.167566,-1.206354,45.51,1.0
181966,125200.0,-0.769172,1.342212,-2.171454,-0.151513,-0.648374,-0.973504,-1.706658,0.313745,-1.982302,...,-0.036122,-0.753591,-0.047113,0.358493,-0.287407,0.476506,0.250531,0.250987,40.00,1.0
182992,125612.0,1.889618,1.073099,-1.678018,4.173268,1.015516,-0.009389,-0.079706,0.064071,-0.714517,...,0.203728,0.733796,-0.036560,0.334306,0.147171,0.279556,0.031669,0.035883,3.22,1.0
183106,125658.0,0.224414,2.994499,-3.432458,3.986519,3.760233,0.165640,1.099378,-0.654557,-2.435416,...,0.491337,-0.984223,-0.421979,-1.048058,0.726412,0.268625,0.283689,0.419102,0.00,1.0
184379,126219.0,-1.141559,1.927650,-3.905356,-0.073943,-0.044858,-1.756999,-1.217416,0.364563,-2.770148,...,0.102081,-0.531496,-0.328741,0.393100,0.568435,0.786605,-0.146102,0.076211,25.00,1.0

In [20]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    368
Name: count, dtype: int64

In [21]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,68260.485772,-0.090131,0.029742,0.374757,0.132762,-0.198695,0.156044,-0.043214,0.083515,0.095448,...,0.044764,-0.016357,-0.051173,0.000461,0.022151,0.045136,0.012137,0.008007,-0.011327,98.100854
1.0,58116.711957,-5.926741,4.330987,-7.884388,4.836685,-4.286202,-1.424070,-6.893932,0.739547,-2.838131,...,0.404833,0.790022,-0.023060,-0.043940,-0.071941,0.080214,0.040915,0.177371,0.050569,115.659891

splitting the data into features & targets

In [23]:
x = new_dataset.drop(columns='Class', axis=1)
y = new_dataset['Class']

In [24]:
print(x)

            Time        V1        V2        V3        V4        V5        V6  \
163637  116108.0  1.904875 -0.039293 -1.861770  0.590780  0.141073 -1.397079
111899   72420.0  1.464097 -0.417452  0.184517 -0.893352 -0.579609 -0.458066
173145  121366.0  2.293280 -0.705780 -1.718465 -1.180551  0.164643 -0.159485
123688   77024.0  0.584567 -1.233131  1.400068  1.754818 -1.247584  1.550662
164510  116772.0 -0.369700  0.764911  0.079105  1.237013  1.391318 -0.237741
...          ...       ...       ...       ...       ...       ...       ...
178208  123525.0 -5.904921  4.439911 -8.631802  7.788684 -4.989580 -1.200144
181966  125200.0 -0.769172  1.342212 -2.171454 -0.151513 -0.648374 -0.973504
182992  125612.0  1.889618  1.073099 -1.678018  4.173268  1.015516 -0.009389
183106  125658.0  0.224414  2.994499 -3.432458  3.986519  3.760233  0.165640
184379  126219.0 -1.141559  1.927650 -3.905356 -0.073943 -0.044858 -1.756999

              V7        V8        V9  ...       V20       V21       V22  \
163637  0.346124 -0.370206  0.624711  ... -0.070335  0.234132  0.673027
111899 -0.508178 -0.179101 -0.825080  ...  0.164745 -0.147869 -0.509332
173145 -0.416908 -0.181577 -0.343069  ...  0.014123 -0.143973 -0.396187
123688 -0.951445  0.604287  1.534106  ...  0.246866  0.120765  0.307101
164510  0.772740 -0.061672 -0.411669  ...  0.214055  0.201544  0.732222
...          ...       ...       ...  ...       ...       ...       ...
178208 -7.674060  4.125761 -5.315778  ... -0.505608  1.775030  1.266441
181966 -1.706658  0.313745 -1.982302  ... -0.102294 -0.036122 -0.753591
182992 -0.079706  0.064071 -0.714517  ... -0.153570  0.203728  0.733796
183106  1.099378 -0.654557 -2.435416  ... -0.200846  0.491337 -0.984223
184379 -1.217416  0.364563 -2.770148  ... -0.250583  0.102081 -0.531496

             V23       V24       V25       V26       V27       V28  Amount
163637 -0.087906 -0.160303  0.209953 -0.101097 -0.014327 -0.017435   79.80
111899 -0.000225 -0.575871  0.388285 -0.423453  0.013825  0.015681   14.39
173145  0.191255 -0.383015 -0.019366 -0.368746 -0.030408 -0.062015    7.95
123688 -0.313366 -0.259121  0.393065 -0.214801  0.073843  0.060423  237.89
164510 -0.150214  0.545925 -0.091192 -0.391430  0.228385  0.237752   36.12
...          ...       ...       ...       ...       ...       ...     ...
178208 -0.199410  0.014960 -0.000019  0.544210 -1.167566 -1.206354   45.51
181966 -0.047113  0.358493 -0.287407  0.476506  0.250531  0.250987   40.00
182992 -0.036560  0.334306  0.147171  0.279556  0.031669  0.035883    3.22
183106 -0.421979 -1.048058  0.726412  0.268625  0.283689  0.419102    0.00
184379 -0.328741  0.393100  0.568435  0.786605 -0.146102  0.076211   25.00

[860 rows x 30 columns]

In [25]:
print(y)

163637    0.0
111899    0.0
173145    0.0
123688    0.0
164510    0.0
         ...
178208    1.0
181966    1.0
182992    1.0
183106    1.0
184379    1.0
Name: Class, Length: 860, dtype: float64

split the data into training data & test data

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [27]:
print(X.shape, X_train.shape, X_test.shape)

(860, 30) (688, 30) (172, 30)

model training

logistic regression

In [28]:
model = LogisticRegression()

In [29]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

model evaluation

accuracy score

In [31]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [32]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9549418604651163

In [33]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [34]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.936046511627907